<?php


class GenerateIconifyPlugin extends Task {
    
	var $requireValidProject = true ;
	
	var $requireProjectType = 'aenoa' ;
	
	private $duplicateRules = array (
			'add' => 'create' ,
			'project' => 'projects'
		) ;
	
	private $ACFRoot ;
	
	private $possiblePaths = array ( 'acf' ) ;
	
	function getOptions ()
	{
		$root = setTrailingDS( dirname(ROOT) ) ;
		
		foreach ( $this->possiblePaths as $path )
		{
			if ( is_dir ( $root.$path.DS.'plugins'.DS.'iconify' ) == true )
			{
				$this->ACFRoot = setTrailingDS($root.$path );
			}
		}
		if ( is_null ( $this->ACFRoot ) )
		{
			$this->manager->cancel ( 'ACF not found.' ) ;
		}
	}
	
	function process ()
	{
		$files = $this->futil->getFilesList ($this->ACFRoot.'plugins'.DS.'iconify'.DS) ;
		
		$cssContent = '/* ACF.plugins.iconify - autogenerated */' ;
		
		$icons = 0 ;
		
		foreach ( $files as $file )
		{
			if ( $file['type'] != 'dir' && ($file['extension'] == 'png' ||  $file['extension'] == 'gif') )
			{
				$icons ++ ;
				$cssContent .= $this->getCSSRule ( $file['filename'] , $file['extension']) ;
			}
		}
		$files = $this->futil->getFilesList ($this->ACFRoot.'plugins'.DS.'iconify'.DS.'social'.DS) ;
		
		foreach ( $files as $file )
		{
			if ( $file['type'] != 'dir' && ($file['extension'] == 'png' ||  $file['extension'] == 'gif') )
			{
				$icons ++ ;
				$cssContent .= $this->getCSSRule ( 'social' . DS . $file['filename'] , $file['extension']) ;
			}
		}
		
		$file = new File ($this->ACFRoot.'plugins'.DS.'iconify'.DS.'iconify-icons.css', false) ;
		if($file->exists())
		{
			$file->delete () ;
		}
		$file->create () ;
		if ( $file->write ( $cssContent ) && $file->close () )
		{
			$this->view->setSuccess ( 'Iconify iconify-icons.css CSS file generated, ' . $icons . ' icons processed.') ;
		} else {
			$this->view->setError ( 'Iconify iconify-icons.css CSS file not generated : an error occured during file writing.') ;
		}
	}
	
	
	private function getCSSRule ( $filename , $ext )
	{
		$str = '' ;
		if ( strstr ( $filename , '_16' ) === false && strstr ( $filename , '_22' ) === false )
		{
			$str .= '.icon.'.str_replace('/','-',$filename);
		
			if ( array_key_exists($filename, $this->duplicateRules) )
			{
				$str .= ',.icon.'.$this->duplicateRules[$filename];
			}
			
			$str .='{background-image:url("'.$filename.'.'.$ext.'");}' ;
			
			if ( $this->futil->fileExists ( $this->ACFRoot.'plugins'.DS.'iconify'.DS . $filename.'_16.'.$ext.'' ) == true )
			{
				$str .= '.icon16.'.str_replace('/','-',$filename);
				
				if ( array_key_exists($filename, $this->duplicateRules) )
				{
					$str .= ',.icon16.'.$this->duplicateRules[$filename] ;
				}
				
				$str .= '{background-image:url("'.$filename.'_16.'.$ext.'");}' ;
			} else {
				$this->view->setError ( 'Icon not found: ' . $this->ACFRoot.'plugins'.DS.'iconify'.DS . $filename.'_16.png|gif', true) ;
			}
			
		}
		return $str ;		
	}
}










































?>